### PR TITLE
Remove python_2_unicode_compatible

### PR DESCRIPTION
**Pull request by ipeterov**
python_2_unicode_compatible support has ended in Django 3.0.0. https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

### CODE REVIEW

**Comment by ipeterov** [comment]
Link issue #55

**Comment by KatherineMichel** [comment]
Thank you for doing this, @ipeterov. I will merge soon and include in a new release. We are working on other apps too, if you are interested in dropping Python 2 support in another one. Let me know if you are interested!

**Comment by ipeterov** [comment]
I'm sorry for not being active here, simply don't have the time :(

I still appreciate your efforts very much.

**Comment by KatherineMichel** [comment]
@ipeterov No problem! Thank you for your interest in the app.

**Pull request merged**
