### PR TITLE
Increase overridability

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Few changes, that makes overriding this project much easier:
- Admin is registered as regular classes
- The `target_content_type` and `target_object_id` fields are not required when editing admin. They are often set blank by `pinax-referrals`, so user can't save existing records.
- The `referral_responses_for_request(cls, request)` function was added, so user can easily get `ReferralResponse` objects for given request.
- Few improvements to the admin search and listing.

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@KatherineMichel Could you please look at this PR? Many thanks :-)

**Comment by KatherineMichel** [comment]
@PetrDlouhy I'll look at it soon. Sorry for the delay!

**Comment by KatherineMichel** [comment]
@PetrDlouhy Thank you for doing that! Sorry it took a while. This will be part of our new release. Would be great to have tests, if you are so inclined to provide. Pinax is getting more caught up, so I won't take so long to review this time!

**Comment by crawfordleeds** [comment]
Hey @PetrDlouhy, thanks for these updates, they're super helpful for a project I'm working on.

What do you recommend as the best mechanism for overriding the admin class. For example, I'd like `created_at` in the list_display for the `ReferralResponseAdmin`. My current thought is to subclass, update list_display, register the new class and unregister the previous `ReferralResponseAdmin`. Is there are better way to override? Thanks!

**Comment by PetrDlouhy** [comment]
@crawfordleeds I usually do the unregistering and registering new class way. But in some simple cases you can also simply assign new function/property to the existing class (although you probably wouldn't be able to use `super()` in the overridden functions):
```python
from pinax.referrals.admin import ReferralResponseAdmin

ReferralResponseAdmin.created_at = models.DateTimeField(
...
)
```

**Comment by crawfordleeds** [comment]
@PetrDlouhy, makes sense thanks for the help!

**Comment by nguyenthanhquang152** [comment]
@PetrDlouhy @KatherineMichel Hi guys, in the commit [d3411eed41fce6599f1de79f43cfb5f8f9266455](https://github.com/pinax/pinax-referrals/commit/d3411eed41fce6599f1de79f43cfb5f8f9266455#), you modified field constraints but didn't make migrations for this change.

**Pull request merged**
